name: Run shell command
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      name: Echo a string
      run: echo "Hello Security DevSecOps"